appname="../build/SICER2"

all:
	rm -f $(appname)
	cat init.py >> $(appname)
	cat pybam.py >> $(appname)
	cat island_threshold.py >> $(appname)
	cat species.py >> $(appname)
	cat functions.py >> $(appname)
	cat application.py >> $(appname)
	chmod +x $(appname)